# Site settings
title: Amazing Disney Collection
header-img: img/home-bg.jpg
email: amazingpro@techimpossible.com
description: "A Place Where Dreams Come True!"
baseurl: ""
url: "https://www.amazingdisneycollection.com/"
twitter_username: Peter_Skaronis
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
